require("dotenv").config();
const connectDB = require("./config/db");
const Product = require("./models/Product");
const Review = require("./models/Review");

// Local, background-removed images — downloaded via download-images.js and
// processed via remove-backgrounds.py into client/public/images/. Served by
// Vite at /images/... — no more dependency on ainak.pk's live site.
const glassesUrls = [
  "/images/eyeglasses-wear_1203-2605.png",
  "/images/louis-vuitton-z1505e-bla-3.png",
  "/images/ray-ban-3447-golden-brown-3.png",
  "/images/rayban-aviator-black-large-3.png",
  "/images/balenciaga-bb0325o-black-3.png",
  "/images/gucci-gg18650-grey-3.png",
  "/images/fame-3234-grey-3.png",
  "/images/ray-ban-r921-black-3.png",
  "/images/louis-vuitton-z1910e-3.png",
  "/images/montblanc-mb0278s-black-3.png",
  "/images/ray-ban-aviator-golden-neww-3.png",
  "/images/gucci-gg0001s-tortoise-3.png",
  "/images/ray-ban-rb3635-gold-brown-3-1.png",
  "/images/rb4343-black-3-new.png",
  "/images/cartier-ct03601o-golden-3.png",
  "/images/cartier-ct03108o-grey-3.png",
  "/images/cartier-ct03362o-new-black-3.png",
  "/images/cartier-ct03162o-golden-3.png",
  "/images/cartier-ct00510-black-3.png",
  "/images/cartier-8200962-gold-3.png",
  "/images/mont-blanc-mb0319s-grey-3.png",
  "/images/ray-ban-rb2168-golden-black-3.png",
  "/images/ray-ban-wayfarer-3.png",
  "/images/ray-ban-rb4228-matte-black-3.png",
  "/images/ray-ban-rb5630-golden-yellow-3.png",
  "/images/ray-ban-rb4364-black-brown-3.png",
  "/images/ray-ban-rb4741-black-3.png",
  "/images/ray-ban-rb4734-matte-black-3.png",
  "/images/ray-ban-rb5607-black-3.png",
  "/images/ray-ban-wayfarer-brown-tortoise-new-3.png"
];

const contactLensUrls = [
  "/images/hydro-lens-watermark-copy-5.png",
  "/images/acuvue-oasys-watermark-2.png",
  "/images/flexcon-1.png",
  "/images/biomedics-55.png",
  "/images/bella-elite-copy-2.png",
  "/images/freshlook-copy-2.png",
  "/images/avaira-lens-1.png",
  "/images/freshkon-mosaic.png"
];

let glassesIdx = 0;
let lensIdx = 0;

const getGlassesImage = () => {
  const url = glassesUrls[glassesIdx % glassesUrls.length];
  glassesIdx++;
  return url;
};

const getLensImage = () => {
  const url = contactLensUrls[lensIdx % contactLensUrls.length];
  lensIdx++;
  return url;
};

const products = [
  {
    name: "Mont Blanc MB0319S",
    brand: "Mont Blanc",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "large",
    price: 14000,
    image: getGlassesImage(),
    colorSwatches: ["#8c8c8c"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Grey",
  },
  {
    name: "Mont Blanc MB0319S",
    brand: "Mont Blanc",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "large",
    price: 14000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Cartier CT0865S",
    brand: "Cartier",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 14000,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37", "#111111"],
    badges: ["New", "Premium"],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Cartier CT0532S",
    brand: "Cartier",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37", "#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Tortoise",
  },
  {
    name: "Cartier CT0533S",
    brand: "Cartier",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#1c3f8c"],
    badges: ["New", "Premium"],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Blue",
  },
  {
    name: "Cartier CT0533S",
    brand: "Cartier",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37", "#111111"],
    badges: ["New", "Premium"],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Mont Blanc MB0381S",
    brand: "Mont Blanc",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "large",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Wayfarer",
    brand: "Ray Ban",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 9500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Hot selling", "Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Mont Blanc MB0381S",
    brand: "Mont Blanc",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "large",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#6b4b2a", "#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Tortoise",
  },

  // ---- Homepage "Premium Sunglasses" section ----
  {
    name: "Ray Ban RB3447",
    brand: "Ray Ban",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 6500,
    image: getGlassesImage(),
    colorSwatches: ["#8c5a1f"],
    badges: [],
    material: "Metal",
    shape: "Round",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Louis Vuitton Z1505E",
    brand: "Louis Vuitton",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Wayfarer Polarized",
    brand: "Ray Ban",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 14500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Polarized", "Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Wayfarer Reverse",
    brand: "Ray Ban",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 14000,
    image: getGlassesImage(),
    colorSwatches: ["#2e4d2e"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Green",
  },
  {
    name: "Cartier CT0865S Aviator",
    brand: "Cartier",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 14000,
    image: getGlassesImage(),
    colorSwatches: ["#2e4d2e", "#d4af37"],
    badges: ["Premium"],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Green/Gold",
  },
  {
    name: "Prada Square",
    brand: "Prada",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Louis Vuitton Square",
    brand: "Louis Vuitton",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Metal",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Aviator Large",
    brand: "Ray Ban",
    subCategory: "premium-sunglasses",
    gender: "men,women",
    size: "large",
    price: 13500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Black",
  },

  // ---- Homepage "Sunglasses For Men & Women" section ----
  {
    name: "Mont Blanc MB0287S",
    brand: "Mont Blanc",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Louis Vuitton Clash Low Square Z1910E",
    brand: "Louis Vuitton",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Gucci GG0001S",
    brand: "Gucci",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 15000,
    image: getGlassesImage(),
    colorSwatches: ["#7a4a2a", "#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Tortoise",
  },
  {
    name: "Prada PSA07",
    brand: "Prada",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 16500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Aviator Gold",
    brand: "Ray Ban",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 12500,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37"],
    badges: ["Premium"],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Ray Ban Round Metal",
    brand: "Ray Ban",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 9500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Metal",
    shape: "Round",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Ray Ban Clubmaster",
    brand: "Ray Ban",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 10500,
    image: getGlassesImage(),
    colorSwatches: ["#8c5a1f", "#111111"],
    badges: ["Premium"],
    material: "Acetate/Metal",
    shape: "Browline",
    rim: "Half rim",
    color: "Brown",
  },
  {
    name: "Ray Ban Aviator Classic",
    brand: "Ray Ban",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 11500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Metal",
    shape: "Aviator",
    rim: "Full rim",
    color: "Black",
  },

  // ---- Contact Lenses ----
  {
    name: "Hydro",
    brand: "Chashmey",
    category: "contact-lenses",
    subCategory: "colored-lenses",
    gender: "unisex",
    size: "medium",
    price: 3600,
    image: getLensImage(),
    colorSwatches: ["#7a5230", "#4a7a6b", "#3a3a3a"],
    badges: [],
    description:
      "1 Box 2 Lenses. Hydro colored contact lenses give a natural tint change while staying soft and comfortable for all-day wear.",
    waterContent: "42% Water",
    diameter: "14.2mm",
    baseCurve: "8.6",
    powerRange: "Plano (no power) to -6.00D (0.25 steps)",
  },
  {
    name: "Acuvue Oasys",
    brand: "Acuvue",
    category: "contact-lenses",
    subCategory: "transparent-lenses",
    gender: "unisex",
    size: "medium",
    price: 12000,
    image: getLensImage(),
    colorSwatches: [],
    badges: [],
    description:
      "1 Box 6 Lenses. Acuvue Oasys bi-weekly disposable contact lenses are secure and comfortable, ensuring comfort and a great visual experience. These lenses must be taken out before sleeping to maintain good eye health.",
    waterContent: "38% Water",
    diameter: "14.0mm",
    baseCurve: "8.4",
    powerRange: "-0.50D to -6.00D (0.25 steps)",
  },
  {
    name: "Flexcon",
    brand: "Flexcon",
    category: "contact-lenses",
    subCategory: "transparent-lenses",
    gender: "unisex",
    size: "medium",
    price: 7600,
    image: getLensImage(),
    colorSwatches: [],
    badges: [],
    description:
      "1 Box 6 Lenses. Flexcon monthly disposable lenses offer reliable clarity and comfort for everyday wear.",
    waterContent: "55% Water",
    diameter: "14.2mm",
    baseCurve: "8.6",
    powerRange: "-0.50D to -8.00D (0.25 steps)",
  },
  {
    name: "Biomedics 55",
    brand: "Biomedics",
    category: "contact-lenses",
    subCategory: "transparent-lenses",
    gender: "unisex",
    size: "medium",
    price: 3500,
    image: getLensImage(),
    colorSwatches: [],
    badges: [],
    description:
      "1 Box 6 Lenses. Biomedics 55 Evolution lenses provide consistent hydration and a smooth, breathable fit throughout the day.",
    waterContent: "55% Water",
    diameter: "14.2mm",
    baseCurve: "8.7",
    powerRange: "-0.50D to -8.00D (0.25 steps)",
  },
  {
    name: "Bella Elite Lenses",
    brand: "Bella",
    category: "contact-lenses",
    subCategory: "colored-lenses",
    gender: "unisex",
    size: "medium",
    price: 5200,
    image: getLensImage(),
    colorSwatches: ["#4a7a6b", "#3a5a8c", "#7a5230", "#3a3a3a"],
    badges: ["Premium"],
    description:
      "1 Box 2 Lenses. Bella Elite colored lenses are designed for a natural-looking tint with soft, all-day comfort.",
    waterContent: "40% Water",
    diameter: "14.5mm",
    baseCurve: "8.6",
    powerRange: "Plano (no power) to -6.00D (0.25 steps)",
  },
  {
    name: "Freshlook Lenses",
    brand: "Freshlook",
    category: "contact-lenses",
    subCategory: "colored-lenses",
    gender: "unisex",
    size: "medium",
    price: 7000,
    image: getLensImage(),
    colorSwatches: ["#4a7a6b", "#3a5a8c", "#7a5230"],
    badges: [],
    description:
      "1 Box 2 Lenses. Freshlook Colorblends lenses blend three colors together for a natural, multi-dimensional look.",
    waterContent: "55% Water",
    diameter: "14.5mm",
    baseCurve: "8.6",
    powerRange: "Plano (no power) to -8.00D (0.25 steps)",
  },
  {
    name: "Avaira Vitality",
    brand: "Avaira",
    category: "contact-lenses",
    subCategory: "colored-lenses",
    gender: "unisex",
    size: "medium",
    price: 4600,
    image: getLensImage(),
    colorSwatches: ["#4a7a6b", "#3a5a8c"],
    badges: [],
    description:
      "1 Box 2 Lenses. Avaira Vitality lenses combine a silicone hydrogel material with vibrant color for comfort and a bold look.",
    waterContent: "46% Water",
    diameter: "14.2mm",
    baseCurve: "8.6",
    powerRange: "-0.50D to -6.00D (0.25 steps)",
  },
  {
    name: "Freshkon Mosaic",
    brand: "Freshkon",
    category: "contact-lenses",
    subCategory: "colored-lenses",
    gender: "unisex",
    size: "medium",
    price: 4500,
    image: getLensImage(),
    colorSwatches: ["#4a7a6b", "#3a5a8c", "#7a5230", "#3a3a3a"],
    badges: [],
    description:
      "1 Box 2 Lenses. Freshkon Mosaic lenses use a mosaic color pattern for a natural, dimensional tint.",
    waterContent: "38% Water",
    diameter: "14.2mm",
    baseCurve: "8.6",
    powerRange: "Plano (no power) to -6.00D (0.25 steps)",
  },

  // ---- Eyeglasses ----
  {
    name: "Ray Ban RX5154",
    brand: "Ray Ban",
    category: "eyeglasses",
    subCategory: "men-glasses",
    gender: "men",
    size: "medium",
    price: 8500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Wayfarer",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Prada VPR 09W",
    brand: "Prada",
    category: "eyeglasses",
    subCategory: "women-glasses",
    gender: "women",
    size: "medium",
    price: 13500,
    image: getGlassesImage(),
    colorSwatches: ["#7a4a2a"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Cat Eye",
    rim: "Full rim",
    color: "Tortoise",
  },
  {
    name: "Gucci GG0269O",
    brand: "Gucci",
    category: "eyeglasses",
    subCategory: "premium-glasses",
    gender: "men,women",
    size: "medium",
    price: 16000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["New", "Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Cartier CT0009O",
    brand: "Cartier",
    category: "eyeglasses",
    subCategory: "premium-glasses",
    gender: "men",
    size: "medium",
    price: 17500,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37"],
    badges: ["Premium"],
    material: "Metal",
    shape: "Rectangle",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Mont Blanc MB0044O",
    brand: "Mont Blanc",
    category: "eyeglasses",
    subCategory: "metal-glasses",
    gender: "men",
    size: "medium",
    price: 15500,
    image: getGlassesImage(),
    colorSwatches: ["#8c8c8c"],
    badges: ["Premium"],
    material: "Metal",
    shape: "Rectangle",
    rim: "Full rim",
    color: "Gunmetal",
  },
  {
    name: "Louis Vuitton My Monogram",
    brand: "Louis Vuitton",
    category: "eyeglasses",
    subCategory: "metal-glasses",
    gender: "men,women",
    size: "medium",
    price: 18000,
    image: getGlassesImage(),
    colorSwatches: ["#d4af37"],
    badges: ["New", "Premium"],
    material: "Metal",
    shape: "Round",
    rim: "Full rim",
    color: "Gold",
  },
  {
    name: "Oliver Peoples Gregory Peck",
    brand: "Oliver Peoples",
    category: "eyeglasses",
    subCategory: "premium-glasses",
    gender: "men,women",
    size: "medium",
    price: 19500,
    image: getGlassesImage(),
    colorSwatches: ["#5a3e24"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Brown",
  },
  {
    name: "Hugo Boss HB1247",
    brand: "Hugo Boss",
    category: "eyeglasses",
    subCategory: "men-glasses",
    gender: "men",
    size: "medium",
    price: 11000,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Moscot Lemtosh",
    brand: "Moscot",
    category: "eyeglasses",
    subCategory: "premium-glasses",
    gender: "men,women",
    size: "medium",
    price: 14500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Chashmey Clear Vision",
    brand: "Chashmey",
    category: "eyeglasses",
    subCategory: "transparent-glasses",
    gender: "men,women",
    size: "medium",
    price: 4500,
    image: getGlassesImage(),
    colorSwatches: ["#c9c9c9"],
    badges: [],
    material: "TR90",
    shape: "Round",
    rim: "Full rim",
    color: "Clear",
  },
  {
    name: "Chashmey Blue Shield",
    brand: "Chashmey",
    category: "eyeglasses",
    subCategory: "blue-light-glasses",
    gender: "men,women",
    size: "medium",
    price: 3800,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: ["Hot selling"],
    material: "TR90",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Chashmey Shade Shift",
    brand: "Chashmey",
    category: "eyeglasses",
    subCategory: "transition-glasses",
    gender: "men,women",
    size: "medium",
    price: 6200,
    image: getGlassesImage(),
    colorSwatches: ["#5a3e24"],
    badges: ["New"],
    material: "Acetate",
    shape: "Square",
    rim: "Full rim",
    color: "Tortoise",
  },
  {
    name: "Chashmey Computer Glasses",
    brand: "Chashmey",
    category: "eyeglasses",
    subCategory: "computer-glasses",
    gender: "men,women",
    size: "medium",
    price: 3500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "TR90",
    shape: "Round",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Chashmey Anti Glare Frame",
    brand: "Chashmey",
    category: "eyeglasses",
    subCategory: "antiglare-glasses",
    gender: "men,women",
    size: "medium",
    price: 3200,
    image: getGlassesImage(),
    colorSwatches: ["#33506B"],
    badges: [],
    material: "TR90",
    shape: "Square",
    rim: "Full rim",
    color: "Blue",
  },

  // ---- Lenses ----
  {
    name: "Chashmey Bifocal Classic",
    brand: "Chashmey",
    category: "lenses",
    subCategory: "bifocal-glasses",
    gender: "men,women",
    size: "medium",
    price: 5500,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Acetate",
    shape: "Rectangle",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Chashmey Progressive Pro",
    brand: "Chashmey",
    category: "lenses",
    subCategory: "progressive-glasses",
    gender: "men,women",
    size: "medium",
    price: 7200,
    image: getGlassesImage(),
    colorSwatches: ["#5a3e24"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Rectangle",
    rim: "Full rim",
    color: "Tortoise",
  },

  // ---- Featured Brand Fill-ins ----
  {
    name: "Oliver Peoples O'Malley Sun",
    brand: "Oliver Peoples",
    category: "sunglasses",
    subCategory: "men-women-sunglasses",
    gender: "men,women",
    size: "medium",
    price: 17000,
    image: getGlassesImage(),
    colorSwatches: ["#5a3e24"],
    badges: ["Premium"],
    material: "Acetate",
    shape: "Round",
    rim: "Full rim",
    color: "Brown",
  },
  {
    name: "David Beckham DB1012",
    brand: "David Beckham",
    category: "eyeglasses",
    subCategory: "men-glasses",
    gender: "men",
    size: "medium",
    price: 9800,
    image: getGlassesImage(),
    colorSwatches: ["#111111"],
    badges: [],
    material: "Metal",
    shape: "Square",
    rim: "Full rim",
    color: "Black",
  },
  {
    name: "Bausch And Lomb Soflens",
    brand: "Bausch And Lomb",
    category: "contact-lenses",
    subCategory: "transparent-lenses",
    gender: "unisex",
    size: "medium",
    price: 6800,
    image: getLensImage(),
    colorSwatches: [],
    badges: [],
    description:
      "1 Box 6 Lenses. Bausch + Lomb SofLens monthly disposable lenses are designed for consistent comfort and reliable vision correction.",
    waterContent: "66% Water",
    diameter: "14.2mm",
    baseCurve: "8.6",
    powerRange: "-0.50D to -9.00D (0.25 steps)",
  },
];

const brandLogos = [
  { name: "Ray Ban", image: getGlassesImage() },
  { name: "Prada", image: getGlassesImage() },
  { name: "Louis Vuitton", image: getGlassesImage() },
  { name: "Gucci", image: getGlassesImage() },
  { name: "Oliver Peoples", image: getGlassesImage() },
  { name: "Mont Blanc", image: getGlassesImage() },
];

const reviews = [
  {
    reviewerName: "Zaheer Baloch",
    rating: 5,
    title: "Excellent",
    body: "Excellent frame in this price range",
    image: getGlassesImage(),
    productName: "Mont Blanc MB0381S",
    size: "Medium",
    reviewedAt: new Date("2025-03-24"),
  },
  {
    reviewerName: "Hania Tareen",
    rating: 5,
    title: "Excellent service and delivery",
    body:
      "Excellent fit. Easy selection and ordering process. Very good price. Excellent service and delivery.",
    productName: "Ray Ban Wayfarer (Black)",
    size: "Medium",
    reviewedAt: new Date("2024-10-24"),
  },
  {
    reviewerName: "Ahmed Raza",
    rating: 4,
    title: "Good value",
    body: "Nice acetate finish, arrived within 2 days. Would order again.",
    productName: "Cartier CT0532S",
    size: "Medium",
    reviewedAt: new Date("2025-01-12"),
  },
  {
    reviewerName: "Sana Malik",
    rating: 5,
    title: "Love it",
    body: "The gold frame looks even better in person. Packaging was premium too.",
    productName: "Louis Vuitton Z1505E",
    size: "Medium",
    reviewedAt: new Date("2025-05-02"),
  },
  {
    reviewerName: "Bilal Khan",
    rating: 5,
    title: "Perfect fit",
    body: "Tried on with the AR preview before ordering — matched exactly what arrived.",
    productName: "Prada PS 01RV",
    size: "Medium",
    reviewedAt: new Date("2025-06-18"),
  },
  {
    reviewerName: "Mehak Fatima",
    rating: 4,
    title: "Good but slow delivery",
    body: "Frame quality is great, but delivery took 4 days instead of the promised 1-3.",
    productName: "Gucci GG0001S",
    size: "Large",
    reviewedAt: new Date("2025-02-08"),
  },
];

const run = async () => {
  await connectDB();
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`Seeded ${products.length} products.`);

  await Review.deleteMany({});
  await Review.insertMany(reviews);
  console.log(`Seeded ${reviews.length} reviews.`);

  console.log("Brand row for the UI (hardcode or fetch via /api/products/brands):");
  console.log(brandLogos.map((b) => b.name).join(", "));
  process.exit(0);
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});